### ISSUE TITLE
Axes draw disconnected from pins in a translated world space

### ISSUE THREAD

**Issue by chrisverwey** [EGjoni/Everything-Will-Be-IK-Processing#2]
First off, thanks so much for creating this library. It's really awesome. 

I was using your code in a processing project and I noticed that the axes were not being drawn over the pins. After debugging I discovered that in my project I was translating and rotating the world space using a global translation/rotation matrix before calling simpledArmature.drawMe. Basically I could rotate my camera view by click/dragging the mouse and applying a rotation matrix or using the arrow keys to apply a translation matrix before drawing.

The bone structure draws just fine with this approach, but the Axes.java drawMe method does a resetMatrix before drawing that seems to cause the axes to draw independent of the bones and pins into the original untransformed world space. 

I guess it's not a problem if both the bones and the axes use the same matrix, but it doesn't make sense for them to draw into different matrixes.

I suppose dAxes.java:drawMe() would have the same problem

**Comment by EGjoni** [comment]
Damn. I knew I shouldn't have been lazy about that.

I'm planning to push an improved version of the base library and processing port at some point in the next couple of weeks, so I should have it fixed then.

In the meantime, if you've devised your own fix, you're welcome to submit a pull request, and I'll merge your code in.

**Comment by chrisverwey** [comment]
I tried just removing the resetMatrix. It gets the axes to draw closer, but there is still something not happy with the coordinates. The rootBone pin at (0,0,0) now draws the axes correctly, but the last bone axes still renders off to one side. 

I've uploaded a two sample Processing projects (one with single and the other double precision) - they both give identical results so you can unit test the two sets. 

This image shows my modified code results.
![Screenshot 2020-12-16](https://user-images.githubusercontent.com/34688754/102340798-9cec1680-3f9f-11eb-9480-38d7450590de.png)  
[NA_lib_test_d.zip](https://github.com/EGjoni/Everything-Will-Be-IK-Processing/files/5702189/NA_lib_test_d.zip)
[NA_lib_test_s.zip](https://github.com/EGjoni/Everything-Will-Be-IK-Processing/files/5702190/NA_lib_test_s.zip)

Mouse click/drag to rotate the world, scroll wheel to zoom. A,S,D,W,C,Space to move the target object around.

My (not quite working) code below.
`	public void drawMe(PApplet p, float size) {
		p.pushMatrix();
		p.stroke(p.color(0,255,0));
		drawRay(p, x_().getRayScaledTo(size));
		p.stroke(p.color(255,0, 0));
		drawRay(p, y_().getRayScaledTo(size));
		p.stroke(p.color(0, 0, 255));
		drawRay(p, z_().getRayScaledTo(size));
		p.popMatrix();
	}`

**Comment by EGjoni** [comment]
Are you creating this solely for the purpose of helping you visualize what's going on?  If so, you may wish to try the v3-rc branch, which has much better built in visualizations and examples. It doesn't allow for mouse based camera orbiting, but the camera does orbit the scene by default on a [turntable which stops whenever you interact with things](https://www.youtube.com/watch?v=8U05I204B5Y). 

Much of the visualization code is meant purely for demo and result-inspection purposes so it's probably not going to be trivial to tweak it. You'd likely be better off rewriting a visualizer from scratch. 

However, if you're intent on building off of the existing visualizer, then changing dAxes.drawMe() in the v3-rc branch to something like the following should do the trick: 

```Java
public void drawMe(PGraphics pg, float size) {	
			pg.noStroke();
			updateGlobal();
			pg.pushMatrix();
			pg.getMatrix().apply(getLocalPMatrix());
			if(renderMode == 1) pg.fill(0,255,0);
			else pg.fill(0,0,0,255); 
			pg.pushMatrix();
			pg.translate(size/2f, 0, 0);
			pg.box(size, size/10f,  size/10f);
			pg.popMatrix();			
			//drawRay(pg, x_().getRayScaledTo(size));
			if(renderMode == 1) pg.fill(255,0, 0);
			else pg.fill(0,0,0,255);
			pg.pushMatrix();
			pg.translate(0, size/2f, 0);
			pg.box(size/10f, size, size/10f);
			pg.popMatrix();
			//drawRay(pg, y_().getRayScaledTo(size));
			if(renderMode == 1) pg.fill(0, 0, 255);
			else pg.fill(0,0,0,255); 
			pg.pushMatrix();
			pg.translate(0, 0, size/2f);
			pg.box(size/10f, size/10f, size);
			pg.popMatrix();
			pg.popMatrix();
		
	}	
```

Modifying the visualization code to allow for extension is outside of the scope of this project, so unfortunately I'll have to mark this as a "nofix" for now. But feel free to ask for help on it if you need any.

**Comment by chrisverwey** [comment]
I was using the library as part of a project to determine the optimal bone count, bone length and constraint settings that will use the minimum amount of battery power for a robotics project I'm working on. I was only trying to visualise the axes to help make sure I set up the constraints correctly. 

I'll definitely take a look at the other branch. That sounds more like what I'm looking for thanks!
