### ISSUE TITLE
Broken Download Links for Library Release

### ISSUE THREAD

**Issue by SableRaf** [EGjoni/Everything-Will-Be-IK-Processing#4]
Hi @EGjoni,

While updating contributions for the Processing website, I noticed that the links for downloading the library are currently returning 404 errors:

- Download Link: http://giftedapprentice.com/ewbIK/ewbIK.zip
- Properties Link: http://giftedapprentice.com/ewbIK/ewbIK.txt

Are there any updated links available for the latest release? I can help update the metadata with the correct information. Let me know!

Thank you for your hard work on this project!

Raphaël de Courville
Processing Community Lead

**Comment by EGjoni** [comment]
Oops. Sorry about that. My server went down a while ago and a lot of files didn't make it. 

I've re-uploaded the .zip and it should now be available at the same URL. However, I can't for the life of me remember what the .txt file was supposed to contain. Is it intended to be identical to the .properties file?

**Comment by SableRaf** [comment]
Thanks @EGjoni! 

Yes, the `.txt` file is the properties files.

> Copy the `library.properties` file from your latest release to a `.txt` file hosted at an address by the same name as your `.zip`, except instead ending in `.txt` (e.g. http://www.example.com/awesomelib.txt)

Source: https://github.com/benfry/processing4/wiki/Library-Basics

**Comment by EGjoni** [comment]
Okay, I think it should be fine now. Thanks for letting me know!

**Comment by SableRaf** [comment]
Thanks a lot!
